name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: 
      - completed

# jobs:
#   build:
#     runs-on: self-hosted
    
#     steps:
#     - name: Pull Docker image from Hub
#       run: sudo docker pull rinkukunwarrao/demo-image-test

#     - name: Run Docker container
#       run: docker run -d -p 3000:3000 --name demo-image-test-container rinkukunwarrao/demo-image-test

# name: CI
# on: ["Build Docker Image"]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
