name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: 
      - completed

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Pull Docker image from Hub
      run: sudo docker pull rinkukunwarrao/demo-image-test

    - name: Run Docker container
      run: docker run -d -p 3000:3000 --name demo-image-test-container rinkukunwarrao/demo-image-test
