name: Build Docker Image
on:
  push:
    branches:
        - master
     
jobs:
 
  build:
        name: push docker image to docker hub
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: login to docker hub
            id: docker-hub
            env:
              username: ${{secrets.DOCKERHUB_USERNAME}}
              password: ${{secrets.DOCKERHUB_PASSWORD}}
              
              
            run: |
              docker login -u $username -p $password
  
     
          - name: build the docker image
            id: build-docker-image-frontend
            run: |
              cd frontend
              docker build . -t rinkukunwarrao/project_frontend:latest
              
          - name: build the docker image
            id: build-docker-image-backend
            run: |
              cd backend
              docker build . -t rinkukunwarrao/project_backend:latest
              
          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@master
            with:
              image-ref: 'rinkukunwarrao/project_frontend:latest'
            #  exit-code: '1'
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'

          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@master
            with:
              image-ref: 'rinkukunwarrao/project_backend:latest'
            #  exit-code: '1'
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'
      
              
      
          - name: Slack Notification
            if: failure()
            uses: rtCamp/action-slack-notify@v2
            env: 
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_T }}
              SLACK_CHANNEL: '#testing'
              SLACK_COLOR: '#FF0000'
              SLACK_MESSAGE: 'Trivy scan failed. The build and deployment process has been halted .'
        
     
  
        
          - name: push the docker image
            id: push-docker-image-frontend
            run: docker push rinkukunwarrao/project_frontend:latest

          - name: push the docker image
            id: push-docker-image-backend
            run: docker push rinkukunwarrao/project_backend:latest
    
 
