name: Build Docker Image
on:
  push:
    branches:
        - master
      # - Test
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
            
            
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -t rinkukunwarrao/demo-image-test:latest
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'rinkukunwarrao/demo-image-test:latest'
            exit-code: '1'
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

            

        - name: Slack Notification
          if: failure()
          uses: rtCamp/action-slack-notify@v2
          env: 
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_T }}
            SLACK_CHANNEL: '#testing'
            SLACK_COLOR: '#3339ff'
            SLACK_MESSAGE: 'Trivy scan failed. The build and deployment process has been halted .'
          
       
        - name: Send Slack Notification
          if: failure()
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: '#testing'
            SLACK_COLOR: '#ff0000'
            SLACK_MESSAGE: 'Trivy scan failed. The build and deployment process has been halted, again .'
            SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN_T }}
          
        - name: push the docker image
          id: push-docker-image
          run: docker push rinkukunwarrao/demo-image-test:latest

         
