name: Deploy Docker Image to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.STAGING_SSH_KEY_NEW }}" > /tmp/jenkins-key.pem
          chmod 600 /tmp/jenkins-key.pem

      - name: SSH to AWS and Pull Docker Image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SSH_HOST_NEW }}
          username: ${{ secrets.TAGING_SSH_USER_NEW }}
          key: /tmp/jenkins-key.pem
          script: |
            # Ensure Docker is installed
            sudo apt-get update
            sudo apt-get install -y docker.io

            # Start Docker service
            sudo systemctl start docker
            sudo systemctl enable docker

            # Pull Docker image from Docker Hub
            sudo docker pull rinkukunwarrao/demo-image-test:latest

            # List Docker images to verify
            sudo docker images
